### ISSUE TITLE
comparison of Array with Array failed 最新版本下报错

### ISSUE THREAD

**Issue by Vibutnum** [beenhero/omniauth-weibo-oauth2#28]
```
Exception:comparison of Array with Array failed
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/parameters.rb:25:in `sort!'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/parameters.rb:25:in `encode'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/utils.rb:182:in `to_query'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/request/url_encoded.rb:13:in `block in call'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/request/url_encoded.rb:21:in `match_content_type'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/request/url_encoded.rb:11:in `call'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/oauth2-1.4.0/lib/oauth2/client.rb:99:in `request'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/oauth2-1.4.0/lib/oauth2/client.rb:146:in `get_token'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/omniauth-weibo-oauth2-0.4.3/lib/omniauth/strategies/weibo.rb:97:in `build_access_token'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:73:in `callback_phase'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:230:in `callback_call'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:187:in `call!'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'
```
降至0.4.2后恢复正常

**Comment by NeverMin** [comment]
可以提供一下 `omniauth.rb` 里的配置格式吗?

**Comment by Vibutnum** [comment]
```
 provider :weibo, ENV['JDXL_WEIBO_ID'], ENV['JDXL_WEIBO_SECRET'], token_params: { redirect_uri: "#{ENV['DOMAIN_NAME']}/auth/weibo/callback" }, image_size: 'original'
```

**Comment by NeverMin** [comment]
试试这样:
```
provider :weibo, ENV['JDXL_WEIBO_ID'], ENV['JDXL_WEIBO_SECRET'], {
  token_params: {
    redirect_uri: "#{ENV['DOMAIN_NAME']}/auth/weibo/callback",
    image_size: 'original'
  }
}
```

**Comment by Vibutnum** [comment]
我在0.4.3 版本下 用你给的配置方法试了下。还是会报同样的错误

**Comment by NeverMin** [comment]
我的环境跟你的很接近, ruby 2.4.1, omniauth 1.6.1

你试试将环境变量 `#{ENV['DOMAIN_NAME']}` 直接死, 如 `http://www.example.com/auth/weibo/callback`

**Comment by Vibutnum** [comment]
依旧不行，你那边是正常的么？

**Comment by NeverMin** [comment]
是的, 我这里一切正常. 或是先不请求 `image_size: 'original'`, 我在新浪的 API 接口找不到.

ref: http://open.weibo.com/apps/YOUR_ID/privilege

**Comment by Vibutnum** [comment]
no，依旧不行.....若是特例，可以先观察观察

**Comment by NeverMin** [comment]
有时需要一些运气！

**Comment by NeverMin** [comment]
BTW: rails v5.1.4

**Comment by Vibutnum** [comment]
rails 一样。正在升级ruby2.4.2试试，上一版ruby为2.4.1

**Comment by Vibutnum** [comment]
Ruby 2.4.2, Rails 5.1.4 下 使用 0.4.3 版本，依旧报错...
但在0.4.2下完美通过....

**Comment by NeverMin** [comment]
两版本之前[只差了这一行](/beenhero/omniauth-weibo-oauth2/blob/master/lib/omniauth/strategies/weibo.rb#L95), 这是新浪出于安全要求双向要带回调 URL, 我的环境目前不能动, 等同事合并之后我测试后回复你.

**Comment by NeverMin** [comment]
Hi @Vibutnum , 久等了, 我按 omniauth 建议使用 `'/auth/:provider/callback'` 的方式修改了一个版本, 我自己测试确定没有问题, 你是否可以忙使用以下的方式试试:

在你的 Gem 指定源:
`gem 'omniauth-weibo-oauth2', git: 'https://github.com/NeverMin/omniauth-weibo-oauth2.git', branch: 'fix-callback-url'`

然后更新:
`bundle install`

因为目前 oauth2 出于安全考虑都要求带 `redirect_uri` 参数, 所以是直接在 gem 里处理, 我是希望也同样适合你的环境, 记得配置简化为:
`provider :weibo, ENV['WEIBO_KEY'], ENV['WEIBO_SECRET']`

Welcome any feedback.

**Comment by Vibutnum** [comment]
Hi @NeverMin, sorry 刚才看到，不过有个好消息。

更换了你给的 Gem 源后，已经成功了。

期待你的新版

**Comment by NeverMin** [comment]
好了, 我已打包上传了, enjoy.
